### ISSUE TITLE
Incorrect authentication cause upload failure

### ISSUE THREAD

**Issue by Nao9syu** [flymzero/webdav_client#2]
Thanks for the good library.

when I set no authentication method, file upload failure.
but other method success.(rename, copy, delete...)

I set the correct authentication method first and upload succeeded.

**Comment by flymzero** [comment]
> 谢谢你的好图书馆。
> 
> 当我没有设置身份验证方法时，文件上传失败。
> 但其他方法成功。（重命名，复制，删除...）
> 
> 我先设置了正确的身份验证方法，然后上传成功。



> Thanks for the good library.
> 
> when I set no authentication method, file upload failure.
> but other method success.(rename, copy, delete...)
> 
> I set the correct authentication method first and upload succeeded.

I re-tested the "writeFromFile" method and it works fine with or without authentication. The webdav server I used for testing is https://github.com/hacdias/webdav.

If you still have problems, please tell me which webdav server you are using, or the sample code of the problem, thanks.

I also found a problem in this test：
1.  if it is authentication, you must use "ping" before using the upload and download method (or the internal has been authenticated).
2.  in the case of no authentication, some methods have problems (because I did not test this case 😅).

I'll try to fix it in the next version

**Comment by Y0ngg4n** [comment]
@flymzero i have the same Problem. This is my dart class: https://github.com/Y0ngg4n/fluffy_board/blob/design/lib/dashboard/WebDavSettings.dart

I am using Nextcloud Webdav Server.
I can create folders but when trying to upload the file i get this error:
```
flutter: Response Text:
flutter: <?xml version="1.0" encoding="utf-8"?>
flutter: <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
flutter:   <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
flutter:   <s:message>No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured</s:message>
flutter: </d:error>
flutter: 
flutter: 
```

**Comment by flymzero** [comment]
I have fixed the issue, please update to the latest version: 1.1.0.

**Comment by Y0ngg4n** [comment]
worked thanks :)
